format_version: 10
pipelines:
  prod-java-pipeline2:
    group: Tomcat
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    environment: Dev
    materials:
      git-228b45a:
        git: git@github.com:vjmax/Terraform_on_AWS.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - prod-Build-stage2:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          prod-Build-job2:
            timeout: 0
            resources:
            - Tomcat1
            tasks:
            - exec:
                arguments:
                - clean
                - install
                command: mvn
                run_if: passed
    - Prod-Deploy-stage2:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: true
        jobs:
          Prod-deployy-job2:
            timeout: 0
            resources:
            - Tomcat1
            tasks:
            - exec:
                arguments:
                - tomcat7:deploy
                command: mvn
